### ISSUE TITLE
Create a Basic GUI

### ISSUE THREAD

**Issue by achuthaperumal** [chandruMec/VisualSense#11]
1. User should be able to select a camera from the available cameras.
2. User should be able to view the Image acquired from the camera.
3. Controls to Start and Stop Acquisition.
4. Scrolling on the Image should enable Zoom In and Zoom Out feature.
5. Basic Processing operations such as Brightness, Contrast, Gamma, and Inversion are needed. And it should be applied when selected.

**Comment by chandruMec** [comment]
I have been removed from this task
